"""
Generate a Frigate configuration snippet.

ringbridge already holds everything needed: the camera name, the RTSP path
and the real stream parameters it reads to build the still. Transferring
those into the Frigate config by hand is error-prone, demonstrably so: on
2026-08-30 that config carried `detect: 1280x720` for all four Ring
cameras while three of them deliver 1920x1080. Renaming one camera meant
updating the name in three places, and the `go2rtc` block was missed once.

What gets written is a standalone block to copy in - the Frigate config
stays in the user's hands. ringbridge never touches it; it lives on a
different host anyway.
"""

import logging
from pathlib import Path

from ringbridge.config import *
from ringbridge.ffmpeg import StreamParameters


log = logging.getLogger(__name__)

DEFAULT_ROLES = ['detect', 'record']
DEFAULT_DETECT_FPS = 5


def _stream_size(clip: Path):
    """Width/height from that camera's most recently downloaded clip."""
    try:
        _, video = StreamParameters(str(clip)).wait()
        w, h = video.get('width'), video.get('height')
        return (int(w), int(h)) if w and h else (None, None)
    except Exception as e:
        log.debug(f"{clip.name}: resolution not determinable ({e})")
        return (None, None)


def export(stream_names) -> None:
    """
    `stream_names` are the sanitised names, i.e. the RTSP paths - the same
    ones that work as Frigate camera names.
    """
    cfg = CONFIG.get('frigate_export') or {}
    if not cfg.get('enabled'):
        return

    out = Path(cfg.get('output_path') or (PATH_VIDEOS / 'frigate-cameras.yml'))
    host = cfg.get('rtsp_host') or CONFIG['rtsp_server']['address']
    port = cfg.get('rtsp_port') or CONFIG['rtsp_server']['port']
    roles = cfg.get('roles') or DEFAULT_ROLES
    defaults = cfg.get('detect_defaults') or {}
    fps = defaults.get('fps', DEFAULT_DETECT_FPS)

    go2rtc, cameras = [], []

    for name in sorted(stream_names):
        clip = PATH_VIDEOS / f"{name}_latest.mp4"
        w, h = _stream_size(clip) if clip.exists() else (None, None)

        go2rtc.append(f"    {name}:\n      - rtsp://{host}:{port}/{name}")

        block = [f"  {name}:",
                 "    ffmpeg:",
                 "      inputs:",
                 f"        - path: rtsp://127.0.0.1:8554/{name}",
                 "          input_args: preset-rtsp-restream",
                 f"          roles: [{', '.join(roles)}]",
                 "    detect:",
                 f"      fps: {fps}"]

        # Order of truth: measured beats configured beats omitted. The
        # measured value comes from the clip that was actually delivered -
        # which is exactly how a mismatch in the Frigate config becomes
        # visible. If it cannot be determined, detect_defaults applies; if
        # that is unset too, the lines are left out and Frigate reads the
        # values itself. Nothing is ever guessed.
        if not (w and h):
            w, h = defaults.get('width'), defaults.get('height')
            if w and h:
                log.debug(f"{name}: resolution not measurable, "
                          f"using detect_defaults")

        if w and h:
            block += [f"      width: {w}", f"      height: {h}"]
        else:
            block += ["      # width/height omitted - not measurable and no",
                      "      # detect_defaults set; Frigate reads them from",
                      "      # the stream itself"]

        cameras.append("\n".join(block))

    text = (
        "# Generated by ringbridge - to be copied into the Frigate config.\n"
        "# The resolutions come from each camera's most recent clip, so they\n"
        "# are the values actually being delivered.\n"
        "# ringbridge never modifies the Frigate config itself.\n\n"
        "go2rtc:\n  streams:\n" + "\n".join(go2rtc) + "\n\n"
        "cameras:\n" + "\n\n".join(cameras) + "\n")

    try:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text)
        log.info(f"Frigate snippet written: {out} ({len(cameras)} cameras)")
    except Exception as e:
        log.error(f"Frigate snippet not writable ({e})")
